-- Insert data into the Menu table
INSERT INTO menus (`MenuItemID`, `MenuItemName`, `Category`, `SubCategory`, `Price`, `Description`) VALUES
('M001', 'Lasagna', 'Italian', 'Pasta', 138.54, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M002', 'Dolmades', 'Greek', 'Appetizer', 74.10, 'Stuffed grape leaves with rice and herbs.'),
('M003', 'Carbonara', 'Italian', 'Pasta', 65.44, 'Pasta with pancetta, egg, and Parmesan cheese.'),
('M004', 'Pide', 'Turkish', 'Flatbread', 110.97, 'Turkish flatbread with cheese or meat filling.'),
('M005', 'Moussaka', 'Greek', 'Casserole', 188.02, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M006', 'Caprese Salad', 'Miscellaneous', 'Miscellaneous', 74.43, 'Fresh tomatoes, mozzarella, and basil drizzled with olive oil.'),
('M007', 'Adana Kebab', 'Turkish', 'Kebab', 93.19, 'Spicy minced meat grilled on skewers.'),
('M008', 'Risotto', 'Miscellaneous', 'Miscellaneous', 167.64, 'Creamy rice cooked with broth and Parmesan.'),
('M009', 'Pide', 'Turkish', 'Flatbread', 50.82, 'Turkish flatbread with cheese or meat filling.'),
('M010', 'Ravioli', 'Italian', 'Pasta', 16.68, 'Pasta squares filled with cheese or meat.'),
('M011', 'Imam Bayildi', 'Miscellaneous', 'Miscellaneous', 56.82, 'Stuffed eggplant with tomatoes and onions.'),
('M012', 'Baklava', 'Greek', 'Dessert', 196.02, 'Sweet pastry made with layers of filo and nuts.'),
('M013', 'Loukoumades', 'Miscellaneous', 'Miscellaneous', 95.85, 'Fried dough balls drizzled with honey.'),
('M014', 'Pide', 'Turkish', 'Flatbread', 59.37, 'Turkish flatbread with cheese or meat filling.'),
('M015', 'Shish Kebab', 'Turkish', 'Kebab', 138.03, 'Grilled meat skewers with vegetables.'),
('M016', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 150.25, 'Traditional Greek bean soup.'),
('M017', 'Ravioli', 'Italian', 'Pasta', 53.46, 'Pasta squares filled with cheese or meat.'),
('M018', 'Pastitsio', 'Miscellaneous', 'Miscellaneous', 170.92, 'Baked pasta with meat sauce and béchamel.'),
('M019', 'Spanakopita', 'Miscellaneous', 'Miscellaneous', 155.57, 'Phyllo pastry filled with spinach and feta cheese.'),
('M020', 'Souvlaki', 'Greek', 'Appetizer', 17.46, 'Grilled skewers of meat served with pita bread.'),
('M021', 'Ravioli', 'Italian', 'Pasta', 91.70, 'Pasta squares filled with cheese or meat.'),
('M022', 'Kuzu Tandir', 'Miscellaneous', 'Miscellaneous', 149.13, 'Slow-cooked lamb served with rice.'),
('M023', 'Adana Kebab', 'Turkish', 'Kebab', 165.77, 'Spicy minced meat grilled on skewers.'),
('M024', 'Calzone', 'Miscellaneous', 'Miscellaneous', 106.36, 'Folded pizza filled with cheese and toppings.'),
('M025', 'Risotto', 'Miscellaneous', 'Miscellaneous', 86.17, 'Creamy rice cooked with broth and Parmesan.'),
('M026', 'Galaktoboureko', 'Miscellaneous', 'Miscellaneous', 101.12, 'Custard-filled pastry soaked in syrup.'),
('M027', 'Lahmacun', 'Turkish', 'Pastry', 30.57, 'Turkish flatbread topped with minced meat.'),
('M028', 'Tzatziki', 'Greek', 'Appetizer', 132.15, 'Yogurt dip with cucumbers and garlic.'),
('M029', 'Pide', 'Turkish', 'Flatbread', 47.16, 'Turkish flatbread with cheese or meat filling.'),
('M030', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 89.46, 'Traditional Greek bean soup.'),
('M031', 'Pastitsio', 'Miscellaneous', 'Miscellaneous', 69.70, 'Baked pasta with meat sauce and béchamel.'),
('M032', 'Tiramisu', 'Miscellaneous', 'Miscellaneous', 185.20, 'Layered dessert with coffee-soaked ladyfingers and mascarpone.'),
('M033', 'Pide', 'Turkish', 'Flatbread', 65.85, 'Turkish flatbread with cheese or meat filling.'),
('M034', 'Tzatziki', 'Greek', 'Appetizer', 169.55, 'Yogurt dip with cucumbers and garlic.'),
('M035', 'Pizza Margherita', 'Italian', 'Pasta', 134.26, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M036', 'Loukoumades', 'Miscellaneous', 'Miscellaneous', 102.78, 'Fried dough balls drizzled with honey.'),
('M037', 'Tzatziki', 'Greek', 'Appetizer', 192.02, 'Yogurt dip with cucumbers and garlic.'),
('M038', 'Spaghetti', 'Italian', 'Pasta', 119.58, 'Traditional spaghetti with marinara sauce.'),
('M039', 'Iskender Kebab', 'Miscellaneous', 'Miscellaneous', 44.97, 'Doner kebab served with yogurt and tomato sauce.'),
('M040', 'Lasagna', 'Italian', 'Pasta', 66.83, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M041', 'Moussaka', 'Greek', 'Casserole', 165.70, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M042', 'Kofte', 'Turkish', 'Pastry', 127.43, 'Grilled spiced meatballs served with bread or rice.'),
('M043', 'Moussaka', 'Greek', 'Casserole', 40.59, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M044', 'Gnocchi', 'Italian', 'Pasta', 68.49, 'Small dumplings made from potatoes, served with sauce.'),
('M045', 'Lasagna', 'Italian', 'Pasta', 44.84, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M046', 'Spanakopita', 'Miscellaneous', 'Miscellaneous', 33.82, 'Phyllo pastry filled with spinach and feta cheese.'),
('M047', 'Gnocchi', 'Italian', 'Pasta', 109.96, 'Small dumplings made from potatoes, served with sauce.'),
('M048', 'Ravioli', 'Italian', 'Pasta', 158.59, 'Pasta squares filled with cheese or meat.'),
('M049', 'Menemen', 'Miscellaneous', 'Miscellaneous', 42.78, 'Eggs scrambled with tomatoes and peppers.'),
('M050', 'Tiramisu', 'Miscellaneous', 'Miscellaneous', 116.61, 'Layered dessert with coffee-soaked ladyfingers and mascarpone.'),
('M051', 'Greek Salad', 'Greek', 'Salad', 144.75, 'Salad with cucumbers, tomatoes, olives, and feta cheese.'),
('M052', 'Lasagna', 'Italian', 'Pasta', 166.25, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M053', 'Baklava', 'Greek', 'Dessert', 148.36, 'Sweet pastry made with layers of filo and nuts.'),
('M054', 'Risotto', 'Miscellaneous', 'Miscellaneous', 171.22, 'Creamy rice cooked with broth and Parmesan.'),
('M055', 'Galaktoboureko', 'Miscellaneous', 'Miscellaneous', 183.20, 'Custard-filled pastry soaked in syrup.'),
('M056', 'Pizza Margherita', 'Italian', 'Pasta', 127.03, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M057', 'Kuzu Tandir', 'Miscellaneous', 'Miscellaneous', 83.44, 'Slow-cooked lamb served with rice.'),
('M058', 'Tiramisu', 'Miscellaneous', 'Miscellaneous', 90.99, 'Layered dessert with coffee-soaked ladyfingers and mascarpone.'),
('M059', 'Borek', 'Turkish', 'Pastry', 165.70, 'Savory pastry filled with cheese or meat.'),
('M060', 'Dolmades', 'Greek', 'Appetizer', 118.30, 'Stuffed grape leaves with rice and herbs.'),
('M061', 'Gyro', 'Greek', 'Sandwich', 55.83, 'Sliced meat served in pita with vegetables and tzatziki.'),
('M062', 'Shish Kebab', 'Turkish', 'Kebab', 78.80, 'Grilled meat skewers with vegetables.'),
('M063', 'Spanakopita', 'Miscellaneous', 'Miscellaneous', 101.12, 'Phyllo pastry filled with spinach and feta cheese.'),
('M064', 'Moussaka', 'Greek', 'Casserole', 116.84, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M065', 'Adana Kebab', 'Turkish', 'Kebab', 63.47, 'Spicy minced meat grilled on skewers.'),
('M066', 'Pide', 'Turkish', 'Flatbread', 45.12, 'Turkish flatbread with cheese or meat filling.'),
('M067', 'Risotto', 'Miscellaneous', 'Miscellaneous', 67.24, 'Creamy rice cooked with broth and Parmesan.'),
('M068', 'Pizza Margherita', 'Italian', 'Pasta', 118.50, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M069', 'Baklava', 'Greek', 'Dessert', 127.03, 'Sweet pastry made with layers of filo and nuts.'),
('M070', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 50.92, 'Traditional Greek bean soup.'),
('M071', 'Gnocchi', 'Italian', 'Pasta', 104.77, 'Small dumplings made from potatoes, served with sauce.'),
('M072', 'Tzatziki', 'Greek', 'Appetizer', 145.22, 'Yogurt dip with cucumbers and garlic.'),
('M073', 'Pide', 'Turkish', 'Flatbread', 57.75, 'Turkish flatbread with cheese or meat filling.'),
('M074', 'Iskender Kebab', 'Turkish', 'Kebab', 146.06, 'Doner kebab served with yogurt and tomato sauce.'),
('M075', 'Menemen', 'Miscellaneous', 'Miscellaneous', 54.72, 'Eggs scrambled with tomatoes and peppers.'),
('M076', 'Spanakopita', 'Miscellaneous', 'Miscellaneous', 146.94, 'Phyllo pastry filled with spinach and feta cheese.'),
('M077', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 159.32, 'Traditional Greek bean soup.'),
('M078', 'Galaktoboureko', 'Miscellaneous', 'Miscellaneous', 138.58, 'Custard-filled pastry soaked in syrup.'),
('M079', 'Baklava', 'Greek', 'Dessert', 139.36, 'Sweet pastry made with layers of filo and nuts.'),
('M080', 'Pizza Margherita', 'Italian', 'Pasta', 177.87, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M081', 'Moussaka', 'Greek', 'Casserole', 178.30, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M082', 'Carbonara', 'Italian', 'Pasta', 165.93, 'Pasta with pancetta, egg, and Parmesan cheese.'),
('M083', 'Ravioli', 'Italian', 'Pasta', 120.95, 'Pasta squares filled with cheese or meat.'),
('M084', 'Pide', 'Turkish', 'Flatbread', 162.57, 'Turkish flatbread with cheese or meat filling.'),
('M085', 'Tzatziki', 'Greek', 'Appetizer', 72.22, 'Yogurt dip with cucumbers and garlic.'),
('M086', 'Gnocchi', 'Italian', 'Pasta', 186.50, 'Small dumplings made from potatoes, served with sauce.'),
('M087', 'Dolmades', 'Greek', 'Appetizer', 128.68, 'Stuffed grape leaves with rice and herbs.'),
('M088', 'Tiramisu', 'Miscellaneous', 'Miscellaneous', 63.46, 'Layered dessert with coffee-soaked ladyfingers and mascarpone.'),
('M089', 'Lasagna', 'Italian', 'Pasta', 117.18, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M090', 'Souvlaki', 'Greek', 'Appetizer', 78.90, 'Grilled skewers of meat served with pita bread.'),
('M091', 'Baklava', 'Greek', 'Dessert', 107.50, 'Sweet pastry made with layers of filo and nuts.'),
('M092', 'Pide', 'Turkish', 'Flatbread', 106.62, 'Turkish flatbread with cheese or meat filling.'),
('M093', 'Carbonara', 'Italian', 'Pasta', 188.21, 'Pasta with pancetta, egg, and Parmesan cheese.'),
('M094', 'Imam Bayildi', 'Miscellaneous', 'Miscellaneous', 117.22, 'Stuffed eggplant with tomatoes and onions.'),
('M095', 'Gyro', 'Greek', 'Sandwich', 164.68, 'Sliced meat served in pita with vegetables and tzatziki.'),
('M096', 'Baklava', 'Greek', 'Dessert', 135.15, 'Sweet pastry made with layers of filo and nuts.'),
('M097', 'Shish Kebab', 'Turkish', 'Kebab', 164.82, 'Grilled meat skewers with vegetables.'),
('M098', 'Pizza Margherita', 'Italian', 'Pasta', 131.14, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M099', 'Gnocchi', 'Italian', 'Pasta', 175.91, 'Small dumplings made from potatoes, served with sauce.'),
('M100', 'Lasagna', 'Italian', 'Pasta', 119.29, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M101', 'Spanakopita', 'Miscellaneous', 'Miscellaneous', 10.37, 'Phyllo pastry filled with spinach and feta cheese.'),
('M102', 'Tzatziki', 'Greek', 'Appetizer', 41.79, 'Yogurt dip with cucumbers and garlic.'),
('M103', 'Calzone', 'Miscellaneous', 'Miscellaneous', 112.36, 'Folded pizza filled with cheese and toppings.'),
('M104', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 106.04, 'Traditional Greek bean soup.'),
('M105', 'Risotto', 'Miscellaneous', 'Miscellaneous', 96.07, 'Creamy rice cooked with broth and Parmesan.'),
('M106', 'Imam Bayildi', 'Miscellaneous', 'Miscellaneous', 157.20, 'Stuffed eggplant with tomatoes and onions.'),
('M107', 'Dolmades', 'Greek', 'Appetizer', 155.92, 'Stuffed grape leaves with rice and herbs.'),
('M108', 'Kuzu Tandir', 'Miscellaneous', 'Miscellaneous', 94.53, 'Slow-cooked lamb served with rice.'),
('M109', 'Spaghetti', 'Italian', 'Pasta', 14.18, 'Traditional spaghetti with marinara sauce.'),
('M110', 'Loukoumades', 'Miscellaneous', 'Miscellaneous', 192.71, 'Fried dough balls drizzled with honey.'),
('M111', 'Borek', 'Turkish', 'Pastry', 15.66, 'Savory pastry filled with cheese or meat.'),
('M112', 'Fettuccine Alfredo', 'Italian', 'Pasta', 102.94, 'Fettuccine pasta with a rich, creamy Alfredo sauce.'),
('M113', 'Fettuccine Alfredo', 'Italian', 'Pasta', 106.85, 'Fettuccine pasta with a rich, creamy Alfredo sauce.'),
('M114', 'Shish Kebab', 'Turkish', 'Kebab', 169.75, 'Grilled meat skewers with vegetables.'),
('M115', 'Moussaka', 'Greek', 'Casserole', 95.52, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M116', 'Baklava', 'Greek', 'Dessert', 107.04, 'Sweet pastry made with layers of filo and nuts.'),
('M117', 'Adana Kebab', 'Turkish', 'Kebab', 171.18, 'Spicy minced meat grilled on skewers.'),
('M118', 'Risotto', 'Miscellaneous', 'Miscellaneous', 10.88, 'Creamy rice cooked with broth and Parmesan.'),
('M119', 'Doner Kebab', 'Turkish', 'Kebab', 32.89, 'Grilled meat served in a pita with vegetables.'),
('M120', 'Borek', 'Turkish', 'Pastry', 57.23, 'Savory pastry filled with cheese or meat.'),
('M121', 'Kofte', 'Turkish', 'Pastry', 17.85, 'Grilled spiced meatballs served with bread or rice.'),
('M122', 'Gyro', 'Miscellaneous', 'Miscellaneous', 130.62, 'Sliced meat served in pita with vegetables and tzatziki.'),
('M123', 'Adana Kebab', 'Turkish', 'Kebab', 183.08, 'Spicy minced meat grilled on skewers.'),
('M124', 'Galaktoboureko', 'Miscellaneous', 'Miscellaneous', 88.97, 'Custard-filled pastry soaked in syrup.'),
('M125', 'Kuzu Tandir', 'Miscellaneous', 'Miscellaneous', 184.00, 'Slow-cooked lamb served with rice.'),
('M126', 'Gnocchi', 'Italian', 'Pasta', 35.43, 'Small dumplings made from potatoes, served with sauce.'),
('M127', 'Tiramisu', 'Miscellaneous', 'Miscellaneous', 138.84, 'Layered dessert with coffee-soaked ladyfingers and mascarpone.'),
('M128', 'Greek Salad', 'Greek', 'Salad', 193.92, 'Salad with cucumbers, tomatoes, olives, and feta cheese.'),
('M129', 'Borek', 'Turkish', 'Pastry', 56.21, 'Savory pastry filled with cheese or meat.'),
('M130', 'Lasagna', 'Italian', 'Pasta', 196.52, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M131', 'Pide', 'Turkish', 'Flatbread', 102.31, 'Turkish flatbread with cheese or meat filling.'),
('M132', 'Fasolada', 'Miscellaneous', 'Miscellaneous', 133.01, 'Traditional Greek bean soup.'),
('M133', 'Lahmacun', 'Turkish', 'Pastry', 144.48, 'Turkish flatbread topped with minced meat.'),
('M134', 'Moussaka', 'Greek', 'Casserole', 59.01, 'Layered dish with eggplant, minced meat, and béchamel.'),
('M135', 'Calzone', 'Miscellaneous', 'Miscellaneous', 143.78, 'Folded pizza filled with cheese and toppings.'),
('M136', 'Ravioli', 'Italian', 'Pasta', 98.27, 'Pasta squares filled with cheese or meat.'),
('M137', 'Lasagna', 'Italian', 'Pasta', 164.93, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M138', 'Calzone', 'Miscellaneous', 'Miscellaneous', 96.01, 'Folded pizza filled with cheese and toppings.'),
('M139', 'Lasagna', 'Italian', 'Pasta', 199.10, 'Layered pasta with meat, cheese, and tomato sauce.'),
('M140', 'Spaghetti', 'Italian', 'Pasta', 117.29, 'Traditional spaghetti with marinara sauce.'),
('M141', 'Minestrone', 'Miscellaneous', 'Miscellaneous', 178.10, 'Hearty vegetable soup with beans and pasta.'),
('M142', 'Ravioli', 'Italian', 'Pasta', 86.36, 'Pasta squares filled with cheese or meat.'),
('M143', 'Tzatziki', 'Greek', 'Appetizer', 151.49, 'Yogurt dip with cucumbers and garlic.'),
('M144', 'Gnocchi', 'Italian', 'Pasta', 75.86, 'Small dumplings made from potatoes, served with sauce.'),
('M145', 'Baklava', 'Greek', 'Dessert', 58.38, 'Sweet pastry made with layers of filo and nuts.'),
('M146', 'Dolmades', 'Greek', 'Appetizer', 58.73, 'Stuffed grape leaves with rice and herbs.'),
('M147', 'Kofte', 'Turkish', 'Pastry', 21.77, 'Grilled spiced meatballs served with bread or rice.'),
('M148', 'Pizza Margherita', 'Italian', 'Pasta', 61.21, 'Classic pizza with tomatoes, mozzarella, and basil.'),
('M149', 'Souvlaki', 'Greek', 'Appetizer', 184.74, 'Grilled skewers of meat served with pita bread.'),
('M150', 'Souvlaki', 'Greek', 'Appetizer', 184.83, 'Grilled skewers of meat served with pita bread.');

